version: '3.7'

services:
  caddy-webdav:
    image: andrewzah/caddy-webdav:2.3.0-alpine3.13
    environment:
      USERNAME: 'andrew'
      HASH: 'JDJhJDE0JHB3N0Roajdlck1TRzhhNFVLNVVNeE9jTU9GRWkzSEdNejVOc1QucWxmQ1pNSS5MUy5PLkpP'
    ports:
      - "6969:6969"
    volumes:
      - "./data/:/data/"

