version: '3.7'

services:
  caddy-webdav:
    image: andrewzah/caddy-webdav:2.4.3-alpine3.13
    environment:
      USERNAME: 'andrew'
      HASH: 'abcdefgh'
    ports:
      - "6969:6969"
    volumes:
      - "./data/:/data/"

